config/routes.rb
Rails.application.routes.draw do

  root 'balls#index'
  resources :trophies

end

app/models/trophy.rb
class Trophy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/balls_controller.rb
class BallsController < ApplicationController
  def index
    @trophies = Trophy.all.order(:id)
    render :index
  end
end

app/controllers/trophies_controller.rb
class TrophiesController < ApplicationController
  before_action :set_trophy, only: [:show, :edit, :update, :destroy]

  def index
    @trophies = Trophy.all
  end

  def show
  end

  def new
    @trophy = Trophy.new
  end

  def edit
  end

  def create
    @trophy = Trophy.new(trophy_params)

    respond_to do |format|
      if @trophy.save
        format.html { redirect_to @trophy, notice: 'Trophy was successfully created.' }
        format.json { render :show, status: :created, location: @trophy }
      else
        format.html { render :new }
        format.json { render json: @trophy.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @trophy.update(trophy_params)
        format.html { redirect_to @trophy, notice: 'Trophy was successfully updated.' }
        format.json { render :show, status: :ok, location: @trophy }
      else
        format.html { render :edit }
        format.json { render json: @trophy.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  @trophy.destroy
  respond_to do |format|
    format.html { redirect_to trophies_url, notice: 'Trophy was successfully destroyed.' }
    format.json { head :no_content }
  end
end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_trophy
    @trophy = Trophy.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trophy_params
    params.require(:trophy).permit(:src, :alt, :description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balls_helper.rb
module BallsHelper
end

app/helpers/trophies_helper.rb
module TrophiesHelper
end

app/views/balls/index.html.erb
<div id="game-wrapper" class="game-body">
  <div class="trophies-nav">Trophies</div>
  <div class="game-nav">Game</div>

  <!-- This is the game container -->
  <div class="game-container">
    <div class="instructions">Touch ball to begin.</div>
    <div class="score">
      Points: <span> 0 </span>
    </div>
    <div class="goal">
      Goal: <span> 1 </span>
    </div>
    <div id="ball"></div>
  </div>

  <!-- This is the trophies container -->
  <!-- This is hidden on page load  -->
  <div class="trophies-container">
    <div class="all-trophies-unlocked"> All trophies unlocked </div>
    <div class="empty-trophies">
      Looks like you do not have any trophies now. <br>
      Try hitting your goal first.
    </div>
    <% @trophies.each do |t| %>
    <div class="card">
      <div class="front">
        <a><img src=<%=t.src%> alt=<%=t.alt%>></a>
      </div>
      <div class="back">
        <%=t.description%>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ball</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trophies/_form.html.erb
<%= form_for(@trophy) do |f| %>
  <% if @trophy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trophy.errors.count, "error") %> prohibited this trophy from being saved:</h2>

      <ul>
      <% @trophy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :src %><br>
    <%= f.text_area :src %>
  </div>
  <div class="field">
    <%= f.label :alt %><br>
    <%= f.text_area :alt %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trophies/edit.html.erb
<div class="admin">
  <h1>Editing Trophy</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @trophy %> |
  <%= link_to 'Back', trophies_path %>
</div>

app/views/trophies/index.html.erb
<div class="admin">
  <p id="notice"><%= notice %></p>

  <h1>Listing Trophies</h1>

  <table>
    <thead>
      <tr>
        <th>Src</th>
        <th>Alt</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @trophies.each do |trophy| %>
      <tr>
        <td><%= trophy.src %></td>
        <td><%= trophy.alt %></td>
        <td><%= trophy.description %></td>
        <td><%= link_to 'Show', trophy %></td>
        <td><%= link_to 'Edit', edit_trophy_path(trophy) %></td>
        <td><%= link_to 'Destroy', trophy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_trophy_path %>
</div>

app/views/trophies/new.html.erb
<div class="admin">
  <h1>New Trophy</h1>

  <%= render 'form' %>

  <%= link_to 'Back', trophies_path %>
</div>

app/views/trophies/show.html.erb
<div class="admin">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Src:</strong>
    <%= @trophy.src %>
  </p>
  
  <p>
    <strong>Alt:</strong>
    <%= @trophy.alt %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @trophy.description %>
  </p>

  <%= link_to 'Edit', edit_trophy_path(@trophy) %> |
  <%= link_to 'Back', trophies_path %>
</div>